app = "decode-blog"
console_command = "php /var/www/html/artisan tinker"
primary_region = "waw"

[build.args]
NODE_VERSION = "18"
PHP_VERSION = "7.4"

[env]
APP_ENV = "production"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "info"
LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
SESSION_DRIVER = "cookie"
SESSION_SECURE_COOKIE = "true"
DB_CONNECTION = "mysql"
DB_HOST = "mysql-25a51819-kairambekovmadi-3bc2.b.aivencloud.com"
DB_PORT = "11597"
DB_DATABASE = "defaultdb"
DB_USERNAME = "avnadmin"
DB_PASSWORD = "AVNS_UPqSFTn1nko8Q7kZhDW"
DB_SSL = "true"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8080  # Убедитесь, что порт правильно указан
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024
