app = "decode-blog"
console_command = "php /var/www/html/artisan tinker"
primary_region = "waw"

[build.args]
NODE_VERSION = "18"
PHP_VERSION = "7.4"

[env]
APP_ENV = "production"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "info"
LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
SESSION_DRIVER = "cookie"
SESSION_SECURE_COOKIE = "true"


[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8080  # Убедитесь, что порт правильно указан
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024
